# Data Analysis
* A process of inspecting, cleansing, transforming and modelling data with the goal of discovering useful information and that supports some decision making based on the analysis

# Tools
### Auto managed tools
* Excel
* Tableau
* Qlik
* looker
* Power BI

### Programming Languages
* Python
* R
* Julia

# Why to use Python for data analysis?
* Simple to learn
* Powerful packages / libraries that you can use for not just data analysis but other tasks as well

# Data Analysis Process
#### Data Extraction
* Excel , CSV
* SQL (Database)
* Web scraping
* JSON , XML
* Buy Data
* Distributed Databases

### Data Cleaning
* Missing Values
* Incorrect types
* Incorrect or invalid values
* Outliers

### Data wrangling
* Hierarchical Data
* Handling categorical data
* Reshaping and transforming structures
* Indexing data for quick access

### Analysis
* Exploration
* Build statistical models
* Correlation
* Hypothesis testing
* Statistical analysis
* Reporting

### Action
* Decision 
* Build Machine Learning models
* Live dashboards and reporting

# Packages / Libraries to use for data analysis in Python
* pandas (Data Analysis )
* matplotlib (Foundational library for visualization)
* numpy   (numerical calculations)
* seaborn (a statistical visualization package)
* statsmodels (Advanced statistical functions)
* scipy   (Advanced scientific computing, linear algebra, image processing)
* scikit learn  (Core library for machine learning)

# Numpy
* It is a core package for numerical computing
* it processes very fast

In [2]:
import numpy

In [30]:
# Matrices
a = numpy.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [38]:
# indexing
# Accessing individual values from an array
# Can be used with any sequence
# positive and negative indexing
print(a[1])
print(a[3])
print(a[4])

3
7
9


In [32]:
print(a[-4])
print(a[-2])

3
7


In [39]:
# slicing
# Accessing group of elements from a sequence (strings, lists, tuple, range, numpy arrays)
# start, stop, step
print(a[1 : 4])
print(a[0 : 5: 2])

[3 5 7]
[1 5 9]


In [28]:
name = "John"
print(name[0])

J


In [23]:
a.size

5

In [4]:
a.dtype

dtype('int32')

In [17]:
b = numpy.array([ [2,4,8,10] , [1,3,5,7], [10,12,14,16] ])

In [13]:
a.shape

(4,)

In [18]:
b.shape

(3, 4)

In [19]:
b.ndim

2

In [21]:
 a = [13, 14, 15, 16]
print(a)
print(type(a))

[13, 14, 15, 16]
<class 'list'>


In [ ]:
# numpy operations
# nump booleans
# pandas data frames